#include "../../include/Variable/variables.h"
#include "../../include/Constitutive_Law/Constitutive_law.h"
#include "../../include/lotus_application.h"
LOTUS_CREATE_VARIABLE(int, SPACE_DIMENSION)

LOTUS_CREATE_VARIABLE(double, TIME)
LOTUS_CREATE_VARIABLE(double, START_TIME)
LOTUS_CREATE_VARIABLE(double, END_TIME)
LOTUS_CREATE_VARIABLE(double, DELTA_TIME)
LOTUS_CREATE_VARIABLE(double, PREVIOUS_DELTA_TIME)
LOTUS_CREATE_VARIABLE(double, INTERNAL_END_TIME)

LOTUS_CREATE_VARIABLE(double, DETERMINANT_F)

LOTUS_CREATE_VARIABLE(double, YOUNG_MODULUS)
LOTUS_CREATE_VARIABLE(double, POISSON_RATIO)

LOTUS_CREATE_VARIABLE(double, TEMPERATURE)
LOTUS_CREATE_VARIABLE(double, THERMAL_EXPANSION_COEFFICIENT)
LOTUS_CREATE_VARIABLE(double, REFERENCE_TEMPERATURE)

LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(DISPLACEMENT)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(VELOCITY)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(ROTATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(ACCELERATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(ANGULAR_ACCELERATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(VOLUME_ACCELERATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(EXTERNAL_FORCE)

LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(FORCE_RESIDUAL )
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(MOMENT_RESIDUAL )
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(INTERNAL_FORCE)

LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(REACTION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(REACTION_MOMENT)

LOTUS_CREATE_VARIABLE(Array, EXTERNAL_FORCES_VECTOR)
LOTUS_CREATE_VARIABLE(Array, RESIDUAL_VECTOR)
LOTUS_CREATE_VARIABLE(Array, EXTERNAL_ENERGY)

LOTUS_CREATE_VARIABLE(double, STRAIN_ENERGY)

LOTUS_CREATE_VARIABLE(double, DENSITY)
LOTUS_CREATE_VARIABLE(double, THICKNESS)
LOTUS_CREATE_VARIABLE(double, ELASTICITY_MODULUS)
LOTUS_CREATE_VARIABLE(double, POISON)

LOTUS_CREATE_VARIABLE(int, NL_ITERATION_NUMBER)

LOTUS_CREATE_VARIABLE(Constitutive_Law::Pointer, CONSTITUTIVE_LAW)


void Lotus_Application::RegisterVariables() {
    LOTUS_REGISTER_VARIABLE(SPACE_DIMENSION)

    //STRATEGIES
    LOTUS_REGISTER_VARIABLE(TIME)
    LOTUS_REGISTER_VARIABLE(START_TIME)
    LOTUS_REGISTER_VARIABLE(END_TIME)
    LOTUS_REGISTER_VARIABLE(DELTA_TIME)
    LOTUS_REGISTER_VARIABLE(PREVIOUS_DELTA_TIME)

    LOTUS_REGISTER_VARIABLE(DETERMINANT_F)

    LOTUS_REGISTER_VARIABLE(YOUNG_MODULUS)
    LOTUS_REGISTER_VARIABLE(POISSON_RATIO)

    LOTUS_REGISTER_VARIABLE(TEMPERATURE)
    LOTUS_REGISTER_VARIABLE(THERMAL_EXPANSION_COEFFICIENT)
    LOTUS_REGISTER_VARIABLE(REFERENCE_TEMPERATURE)

    //ROTATION
    //movement
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ROTATION)
    //reaction
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(REACTION_MOMENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(REACTION)
    //movement time derivatives
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_ACCELERATION)
    //DISPLACEMENT
    // Movement time derivatives
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY)
    // Movement
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT)
    //reaction
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(REACTION)

    //EXTERNAL CONDITIONS
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VOLUME_ACCELERATION)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FORCE_RESIDUAL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENT_RESIDUAL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(INTERNAL_FORCE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(EXTERNAL_FORCE)

    LOTUS_REGISTER_VARIABLE(EXTERNAL_FORCES_VECTOR)
    LOTUS_REGISTER_VARIABLE(RESIDUAL_VECTOR)

    //CONSTITUTIVE LAW AND PROPERTIES
    LOTUS_REGISTER_VARIABLE(CONSTITUTIVE_LAW)
    LOTUS_REGISTER_VARIABLE(DENSITY)
    LOTUS_REGISTER_VARIABLE(THICKNESS)

    LOTUS_REGISTER_VARIABLE(EXTERNAL_ENERGY)
    LOTUS_REGISTER_VARIABLE(STRAIN_ENERGY)

    LOTUS_REGISTER_VARIABLE(NL_ITERATION_NUMBER)
}