#include "../../include/Variable/variables.h"
#include "../../include/Constitutive_Law/Constitutive_law.h"
#include "../../include/lotus_application.h"
LOTUS_CREATE_VARIABLE(int, SPACE_DIMENSION)

LOTUS_CREATE_VARIABLE(double, TIME)
LOTUS_CREATE_VARIABLE(double, START_TIME)
LOTUS_CREATE_VARIABLE(double, END_TIME)
LOTUS_CREATE_VARIABLE(double, DELTA_TIME)
LOTUS_CREATE_VARIABLE(double, PREVIOUS_DELTA_TIME)
LOTUS_CREATE_VARIABLE(double, INTERNAL_END_TIME)

LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(DISPLACEMENT)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(VELOCITY)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(ROTATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(ACCELERATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(ANGULAR_ACCELERATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(VOLUME_ACCELERATION)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(EXTERNAL_FORCE)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(EXTERNAL_MOMENT)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(FORCE_RESIDUAL )
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(MOMENT_RESIDUAL )
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(INTERNAL_FORCE)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(FORCE_LOAD)
LOTUS_CREATE_3D_VARIABLES_WITH_COMPONENTS(POINT_LOAD)


LOTUS_CREATE_VARIABLE(Array, EXTERNAL_FORCES_VECTOR)
LOTUS_CREATE_VARIABLE(Array, RESIDUAL_VECTOR)
LOTUS_CREATE_VARIABLE(Array, EXTERNAL_ENERGY)
LOTUS_CREATE_VARIABLE(Array, FORCE_LOAD_VECTOR)

LOTUS_CREATE_VARIABLE(double, DENSITY)
LOTUS_CREATE_VARIABLE(double, THICKNESS)
LOTUS_CREATE_VARIABLE(double, ELASTICITY_MODULUS)
LOTUS_CREATE_VARIABLE(double, POISON)

LOTUS_CREATE_VARIABLE(Constitutive_Law::Pointer, CONSTITUTIVE_LAW)


void Lotus_Application::RegisterVariables() {
    LOTUS_REGISTER_VARIABLE(SPACE_DIMENSION)

    //STRATEGIES
    LOTUS_REGISTER_VARIABLE(TIME)
    LOTUS_REGISTER_VARIABLE(START_TIME)
    LOTUS_REGISTER_VARIABLE(END_TIME)
    LOTUS_REGISTER_VARIABLE(DELTA_TIME)
    LOTUS_REGISTER_VARIABLE(PREVIOUS_DELTA_TIME)

    //ROTATION
    //movement
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ROTATION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DELTA_ROTATION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(STEP_ROTATION)
    //reaction
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(REACTION_MOMENT)
    //movement time derivatives
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_VELOCITY)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_ACCELERATION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_LAPLACIAN)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_LAPLACIAN_RATE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_COMPONENT_GRADIENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_X_GRADIENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_Y_GRADIENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_Z_GRADIENT)
    //DISPLACEMENT
    // Movement time derivatives
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VELOCITY)
    // Movement
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(STEP_DISPLACEMENT)
    //reaction
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(REACTION)

    //EXTERNAL CONDITIONS
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VOLUME_ACCELERATION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FORCE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(TORQUE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FACE_LOAD)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(NORMAL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(TANGENT_XI)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(TANGENT_ETA)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(LOCAL_TANGENT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(BODY_FORCE)  //to be deleted ?

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FORCE_RESIDUAL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENT_RESIDUAL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(INTERNAL_FORCE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(EXTERNAL_FORCE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(CONTACT_FORCE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(CONTACT_NORMAL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(TEMPERATURE_GRADIENT)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(LINEAR_MOMENTUM)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_MOMENTUM)

    LOTUS_REGISTER_VARIABLE(EXTERNAL_FORCES_VECTOR)
    LOTUS_REGISTER_VARIABLE(RESIDUAL_VECTOR)

    //CONSTITUTIVE LAW AND PROPERTIES
    LOTUS_REGISTER_VARIABLE(CONSTITUTIVE_LAW)
    LOTUS_REGISTER_VARIABLE(DENSITY)
    LOTUS_REGISTER_VARIABLE(THICKNESS)

    LOTUS_REGISTER_VARIABLE(EXTERNAL_ENERGY)

    // LAGRANGE MULTIPLIER
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(VECTOR_LAGRANGE_MULTIPLIER)

    //--------------- GENERAL VARIABLES FOR MULTIPLE APPLICATIONS -------------------//

    //--------------- Geometrical Application -------------------//

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(CHARACTERISTIC_GEOMETRY_LENGTH)

    //--------------- Geometrical Application -------------------//

    //--------------- STRUCTURAL Application -------------------//

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DISTANCE_GRADIENT)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(LAGRANGE_DISPLACEMENT)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DETERMINANT)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ELEMENTSHAPE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MESH_VELOCITY)

    //--------------- ALE Application -------------------//

    //--------------- Adjoint Fluid Application -------------------//
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VECTOR_1 )
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VECTOR_2 )
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VECTOR_3 )
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( AUX_ADJOINT_VECTOR_1 )
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(SHAPE_SENSITIVITY)

    //--------------- Meshing ApplicationApplication -------------------//

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(NODAL_ERROR_COMPONENTS)

    //--------------- PFEM fluids Application -------------------//
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(GRAVITY)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(NORMAL_TO_WALL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(STRUCTURE_VELOCITY)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DRAG_FORCE)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(EMBEDDED_VELOCITY)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FRACT_VEL)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ROTATION_CENTER)

    //--------------- PFEM fluids Application -------------------//

    //--------------- Other Applications -------------------//

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(SEEPAGE_DRAG)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MASS)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(RHS)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(FORCE_CM)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM_CM)

    //       LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS( xi_c )
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DIRECTION)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(Y)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(LOCAL_AXIS_1)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(LOCAL_AXIS_2)
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(LOCAL_AXIS_3)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(NODAL_VAUX)

    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(INTEGRATION_COORDINATES)


    //--------------- Geometry Variables -------------------//
    LOTUS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(PARAMETER_2D_COORDINATES)

}