#ifndef _VARIABLES_H_
#define _VARIABLES_H_
#include "../define.h"
#include "variable.h"
#include "../lotus_components.h"

LOTUS_DEFINE_VARIABLE(int, SPACE_DIMENSION)

LOTUS_DEFINE_VARIABLE(double, TIME)
LOTUS_DEFINE_VARIABLE(double, START_TIME)
LOTUS_DEFINE_VARIABLE(double, END_TIME)
LOTUS_DEFINE_VARIABLE(double, DELTA_TIME)
LOTUS_DEFINE_VARIABLE(double, PREVIOUS_DELTA_TIME)
LOTUS_DEFINE_VARIABLE(double, INTERNAL_END_TIME)

LOTUS_DEFINE_VARIABLE(double, DETERMINANT_F)

LOTUS_DEFINE_VARIABLE(double, YOUNG_MODULUS)
LOTUS_DEFINE_VARIABLE(double, POISSON_RATIO)

LOTUS_DEFINE_VARIABLE(double, TEMPERATURE)
LOTUS_DEFINE_VARIABLE(double, THERMAL_EXPANSION_COEFFICIENT)
LOTUS_DEFINE_VARIABLE(double, REFERENCE_TEMPERATURE)

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, DISPLACEMENT)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, VELOCITY)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, ROTATION)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, ACCELERATION)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, ANGULAR_ACCELERATION)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, VOLUME_ACCELERATION)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, EXTERNAL_FORCE )

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, FORCE_RESIDUAL )
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, MOMENT_RESIDUAL )
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, INTERNAL_FORCE )

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, REACTION)
LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, REACTION_MOMENT)

typedef std::array<double,3> 
                                                    Array;
LOTUS_DEFINE_VARIABLE(Array, EXTERNAL_FORCES_VECTOR)
LOTUS_DEFINE_VARIABLE(Array, RESIDUAL_VECTOR)
LOTUS_DEFINE_VARIABLE(Array, EXTERNAL_ENERGY)

LOTUS_DEFINE_VARIABLE(double, STRAIN_ENERGY)

LOTUS_DEFINE_VARIABLE(double, DENSITY)
LOTUS_DEFINE_VARIABLE(double, ELASTICITY_MODULUS)
LOTUS_DEFINE_VARIABLE(double, POISON)
LOTUS_DEFINE_VARIABLE(double, THICKNESS)

#endif