#ifndef _LOTUS_SOLID_MECHANICS_VARIABLES_H_
#define _LOTUS_SOLID_MECHANICS_VARIABLES_H_
#include "../../../include/Variable/variables.h"
#include "../../../include/lotus_application.h"

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, POINT_LOAD)

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, FORCE_LOAD)
LOTUS_DEFINE_VARIABLE(Array, FORCE_LOAD_VECTOR)

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS( double, MOMENT_LOAD )
LOTUS_DEFINE_VARIABLE(Array, MOMENT_LOAD_VECTOR )

LOTUS_DEFINE_3D_VARIABLES_WITH_COMPONENTS(double, EXTERNAL_MOMENT )

#endif