#ifndef _SOLVE_LOCAL_FLAGS_H_
#define _SOLVE_LOCAL_FLAGS_H_
#include "../define.h"
#include "../Container/flags.h"

class Solver_Local_Flags
{
    public:
        /// Flags for the solution control:
        LOTUS_DEFINE_LOCAL_FLAGS( INITIALIZED );
        LOTUS_DEFINE_LOCAL_FLAGS( CONVERGED );
        LOTUS_DEFINE_LOCAL_FLAGS( DOFS_INITIALIZED );
        LOTUS_DEFINE_LOCAL_FLAGS( ELEMENTS_INITIALIZED );
        LOTUS_DEFINE_LOCAL_FLAGS( CONDITIONS_INITIALIZED );
        LOTUS_DEFINE_LOCAL_FLAGS( ADAPTIVE_SOLUTION );

        /// Flags for the solution options:
        LOTUS_DEFINE_LOCAL_FLAGS( MOVE_MESH );
        LOTUS_DEFINE_LOCAL_FLAGS( UPDATE_VARIABLES );
        LOTUS_DEFINE_LOCAL_FLAGS( REFORM_DOFS );
        LOTUS_DEFINE_LOCAL_FLAGS( INCREMENTAL_SOLUTION );
        LOTUS_DEFINE_LOCAL_FLAGS( COMPUTE_REACTIONS );
        LOTUS_DEFINE_LOCAL_FLAGS( CONSTANT_SYSTEM_MATRIX );
        LOTUS_DEFINE_LOCAL_FLAGS( RAYLEIGH_DAMPING );
        LOTUS_DEFINE_LOCAL_FLAGS( IMPLEX );
};

class Criterias_Local_Flags
{
    public:
    /// Flags for the solution control:
    LOTUS_DEFINE_LOCAL_FLAGS( INITIALIZED );
    LOTUS_DEFINE_LOCAL_FLAGS( INCREMENTAL );
    LOTUS_DEFINE_LOCAL_FLAGS( CONVERGED );
    LOTUS_DEFINE_LOCAL_FLAGS( AND );
    LOTUS_DEFINE_LOCAL_FLAGS( OR );
    LOTUS_DEFINE_LOCAL_FLAGS( UPDATE_RHS );
    LOTUS_DEFINE_LOCAL_FLAGS( SUPPLIED_DOF );
};

class  Time_Integration_Local_Flags
{
 public:
    LOTUS_DEFINE_LOCAL_FLAGS( PREDICT_PRIMARY_VARIABLE );

};
#endif